#!/usr/bin/env python

import urllib
import crypt
import getpass

print("Getting a random salt from random.org...")
salt = urllib.request.urlopen(
    "https://www.random.org/strings/\?num\=1\&len\=20\&digits\=on\&upperalpha\=on\&loweralpha\=on\&unique\=on\&format\=plain\&rnd\=new")

print(crypt.crypt(getpass.getpass(), "$6${}".format(salt)))
